### ISSUE TITLE
Seems like data-set FacebookWall is no longer available!

### ISSUE THREAD

**Issue by holoword** [houchengbin/GloDyNE#2]
Could you please give an copy of it?

**Comment by houchengbin** [comment]
> Could you please give a copy of it?

Please try this link at http://konect.uni-koblenz.de/networks/facebook-wosn-wall

**Comment by houchengbin** [comment]
Most datasets in http://konect.uni-koblenz.de are no longer available.
If one wants to access this dataset, please check http://konect.cc/networks/
